# Mosaic asc art editor build script
Import ('env')

src = Glob ("???[!c]*.c")	# everybody but 'moscat.c'
cat_src = ['color.c', 'mosaic.c', 'moscat.c'],

env.Program ('maae', src)
env.Program ('moscat', cat_src)
